/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "secondary-fixed-dim": "#c0c7d6",
              "on-tertiary-container": "#ffede6",
              "primary": "#004ac6",
              "background": "#faf8ff",
              "primary-container": "#2563eb",
              "surface-container": "#ededf6",
              "primary-fixed-dim": "#b4c5ff",
              "on-secondary": "#ffffff",
              "border-subtle": "#E5E7EB",
              "on-background": "#191b22",
              "surface-container-high": "#e7e7f0",
              "surface-container-lowest": "#ffffff",
              "surface-variant": "#e2e2eb",
              "on-error": "#ffffff",
              "inverse-on-surface": "#f0f0f9",
              "tertiary-fixed-dim": "#ffb596",
              "surface-container-highest": "#e2e2eb",
              "tertiary-container": "#bc4800",
              "on-primary-container": "#eeefff",
              "on-primary-fixed": "#00174b",
              "surface-dim": "#d9d9e2",
              "on-error-container": "#93000a",
              "outline": "#737686",
              "tertiary": "#943700",
              "tertiary-fixed": "#ffdbcd",
              "error-container": "#ffdad6",
              "surface": "#faf8ff",
              "on-primary-fixed-variant": "#003ea8",
              "on-secondary-fixed": "#151c27",
              "on-secondary-fixed-variant": "#404754",
              "on-primary": "#ffffff",
              "on-tertiary": "#ffffff",
              "surface-background": "#FFFFFF",
              "on-tertiary-fixed-variant": "#7d2d00",
              "on-tertiary-fixed": "#360f00",
              "primary-fixed": "#dbe1ff",
              "secondary-container": "#dce2f3",
              "secondary-fixed": "#dce2f3",
              "text-secondary": "#6B7280",
              "on-secondary-container": "#5e6572",
              "inverse-surface": "#2e3037",
              "secondary": "#585f6c",
              "surface-container-low": "#f3f3fc",
              "surface-bright": "#faf8ff",
              "error": "#ba1a1a",
              "outline-variant": "#c3c6d7",
              "on-surface-variant": "#434655",
              "text-primary": "#0F1117",
              "inverse-primary": "#b4c5ff",
              "on-surface": "#191b22",
              "surface-tint": "#0053db"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "spacing": {
              "xs": "4px",
              "md": "16px",
              "base": "8px",
              "gutter": "16px",
              "sm": "8px",
              "xl": "32px",
              "margin-mobile": "16px",
              "lg": "24px",
              "xxl": "48px",
              "margin-desktop": "32px"
      },
      "fontFamily": {
              "body-md": ["Inter", "sans-serif"],
              "headline-lg": ["Inter", "sans-serif"],
              "body-lg": ["Inter", "sans-serif"],
              "headline-sm": ["Inter", "sans-serif"],
              "headline-md": ["Inter", "sans-serif"],
              "mono-label": ["Courier Prime", "monospace"],
              "label-md": ["Inter", "sans-serif"]
      },
      "fontSize": {
              "body-md": ["14px", {"lineHeight": "1.6", "letterSpacing": "0em", "fontWeight": "400"}],
              "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600"}],
              "body-lg": ["16px", {"lineHeight": "1.6", "letterSpacing": "0em", "fontWeight": "400"}],
              "headline-sm": ["18px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}],
              "headline-md": ["24px", {"lineHeight": "1.2", "letterSpacing": "-0.015em", "fontWeight": "600"}],
              "mono-label": ["13px", {"lineHeight": "1", "letterSpacing": "0em", "fontWeight": "400"}],
              "label-md": ["12px", {"lineHeight": "1", "letterSpacing": "0.02em", "fontWeight": "500"}]
      }
    }
  },
  plugins: [],
}
